// ============================================================
//  ESP32 WinKeyer — keyer core
//
//  Iambic A/B state machine, paddle inputs, key/PTT outputs,
//  LEDC sidetone, speed pot. Ticks at 1 kHz in its own FreeRTOS
//  task on core 1, priority above the Arduino loop, so element
//  timing is unaffected by WiFi/MQTT work.
//
//  Timing: PARIS standard — dit = 1200/WPM ms, dah = 3 dits,
//  inter-element = 1 dit, inter-char = 3 dits, word = 7 dits.
//  Weighting shifts the mark/space balance without changing WPM;
//  ratio changes dah length; Farnsworth stretches only the gaps.
//
//  Iambic semantics (Curtis): both modes latch the opposite
//  paddle during an element; mode B also latches during the
//  inter-element space, mode A decides from the live paddles.
//
//  Reference: K3ng CW keyer (Anthony Good K3NG) for behaviour;
//  implementation is original.
// ============================================================

#include "keyer.h"
#include "pins.h"

// ── Morse table ───────────────────────────────────────────
static const struct { char c; const char* p; } MORSE[] = {
  {'A', ".-"},    {'B', "-..."},  {'C', "-.-."},  {'D', "-.."},
  {'E', "."},     {'F', "..-."},  {'G', "--."},   {'H', "...."},
  {'I', ".."},    {'J', ".---"},  {'K', "-.-"},   {'L', ".-.."},
  {'M', "--"},    {'N', "-."},    {'O', "---"},   {'P', ".--."},
  {'Q', "--.-"},  {'R', ".-."},   {'S', "..."},   {'T', "-"},
  {'U', "..-"},   {'V', "...-"},  {'W', ".--"},   {'X', "-..-"},
  {'Y', "-.--"},  {'Z', "--.."},
  {'0', "-----"}, {'1', ".----"}, {'2', "..---"}, {'3', "...--"},
  {'4', "....-"}, {'5', "....."}, {'6', "-...."}, {'7', "--..."},
  {'8', "---.."}, {'9', "----."},
  {'.', ".-.-.-"}, {',', "--..--"}, {'?', "..--.."}, {'/', "-..-."},
  {'=', "-...-"},  {'+', ".-.-."},  {'-', "-....-"}, {'@', ".--.-."},
  {':', "---..."}, {';', "-.-.-."}, {'\'', ".----."}, {'"', ".-..-."},
  {'(', "-.--."},  {')', "-.--.-"}, {'!', "-.-.--"},  {'&', ".-..."},
  {'$', "...-..-"}, {'_', "..--.-"},
};

static const char* morseFor(char c) {
  for (auto& e : MORSE)
    if (e.c == c) return e.p;
  return nullptr;
}

// Reverse lookup for paddle echo. This is not signal decoding: the keyer
// generated these elements itself and knows exactly what they were, so the
// pattern is exact and the only judgement needed is where a character ends.
static char charFor(const char* pat) {
  for (auto& e : MORSE)
    if (!strcmp(e.p, pat)) return e.c;
  return '\0';
}

namespace {

// ── Configuration (written from loop task, read by keyer task) ──
volatile uint8_t   cfgWpm       = 20;
volatile uint8_t   cfgWeight    = 50;
volatile uint8_t   cfgRatio     = 50;
volatile uint8_t   cfgFarns     = 0;
volatile KeyerMode cfgMode      = KEYER_IAMBIC_B;
volatile bool      cfgSwap      = false;
volatile bool      cfgSidetone  = true;
volatile uint16_t  cfgToneHz    = 600;
volatile bool      cfgPtt       = true;
volatile bool      cfgKeyOut    = true;
// Which radio the key and PTT lines drive: bit 0 = radio 1, bit 1 = radio 2.
// Both at once is allowed on purpose — it is how you drive a rig plus an
// amp, monitor or second receiver — but it does mean two transmitters can
// be keyed together, so it is never the default.
volatile uint8_t   cfgRadio     = 1;
// When false the keyer stops sequencing PTT itself and something else owns
// the line via pttManual(). Used on the Flex backend: buffered text there
// is generated by the RADIO, and timing the line from the local monitor
// copy meant two independent generators drifting apart over a message.
volatile bool      cfgPttAuto   = true;
volatile uint16_t  cfgLeadMs    = 50;
volatile uint16_t  cfgTailMs    = 250;
volatile bool      cfgPotEn     = false;   // off until a pot is wired — GPIO34 floats
volatile uint8_t   cfgPotMin    = 10;
volatile uint8_t   cfgPotRange  = 25;

// ── Derived timing, recomputed whenever the above change ──
volatile uint16_t tMarkDit = 60, tMarkDah = 180;   // key-down durations
volatile uint16_t tGapElem = 60;                   // inter-element space
volatile uint16_t tGapChar = 120;                  // *additional* after a character
volatile uint16_t tGapWord = 240;                  // *additional* for a space
// The same timings with the operator's flavour removed — weight 50, ratio
// 50, no Farnsworth. Used ONLY for the local sidetone copy of text the
// FlexRadio is transmitting: the radio has no weighting or Farnsworth (it
// exposes speed/iambic/break_in/qsk and nothing else), so a sidetone made
// with them drifts against the air. Manoj's 33 WPM + Farnsworth 20 ran the
// sidetone ~1 s behind a 21-character memory, which sounds exactly like the
// radio unkeying early. Paddle sending is untouched: there the radio follows
// our elements, so weight and Farnsworth really are on the air.
volatile uint16_t tMarkDitP = 60, tMarkDahP = 180;
volatile uint16_t tGapElemP = 60, tGapCharP = 120, tGapWordP = 240;

void recalc() {
  uint16_t unit = 1200 / (cfgWpm ? cfgWpm : 20);
  // Weighting moves the mark/space boundary without changing overall WPM.
  uint32_t w = cfgWeight ? cfgWeight : 50;
  tMarkDit = (uint16_t)((unit * 2 * w) / 100);
  tGapElem = (uint16_t)(unit * 2 - tMarkDit);
  if (tMarkDit < 5) tMarkDit = 5;
  if (tGapElem < 5) tGapElem = 5;
  // Ratio: nominal 50 → dah is 3 dits.
  tMarkDah = (uint16_t)((uint32_t)tMarkDit * 3 * (cfgRatio ? cfgRatio : 50) / 50);
  // Farnsworth stretches only the inter-character and word gaps.
  uint16_t gapUnit = unit;
  if (cfgFarns >= 5 && cfgFarns < cfgWpm) gapUnit = 1200 / cfgFarns;
  tGapChar = gapUnit * 2;
  tGapWord = gapUnit * 4;

  // Plain profile: what the radio will actually send at this speed.
  tMarkDitP = unit;
  tGapElemP = unit;
  if (tMarkDitP < 5) tMarkDitP = 5;
  if (tGapElemP < 5) tGapElemP = 5;
  tMarkDahP = (uint16_t)(unit * 3);
  tGapCharP = (uint16_t)(unit * 2);
  tGapWordP = (uint16_t)(unit * 4);
}

// ── Cross-task signalling ──
QueueHandle_t  charQ;
volatile bool  flagClear    = false;
volatile bool  flagTune     = false;
volatile bool  flagPttHold  = false;
// WinKeyer BREAKIN is a LEVEL: up from the operator's first element until the
// paddle hang time runs out (one word space plus a dit after the last
// element, the K1EL default), then down. Measured on a genuine WK3.1.
volatile bool  paddleSess   = false;
uint32_t       paddleIdleMs = 0;

// ── Keyer-task state ──
enum State : uint8_t { ST_IDLE, ST_LEAD, ST_KEYDOWN, ST_GAP, ST_TUNE };
volatile State state = ST_IDLE;
uint32_t timerMs     = 0;
bool     curIsDah    = false;
bool     curIsAuto   = false;   // current element from buffer (vs paddles)
bool     lastWasDah  = false;
bool     memDit      = false, memDah = false;
bool     mergeNext   = false;   // suppress the gap after the next character
const char* pattern  = nullptr; // remaining elements of the char being sent
bool     pttOn       = false;
uint32_t tailTimer   = 0;
volatile bool keyDownFlag = false;
// Stamped in the 1 kHz task, so it cannot miss an element. A display
// sampling keyIsDown() at its own rate aliases badly — a dit at 22 WPM is
// 55 ms — and shows a random-looking flicker instead of activity.
volatile uint32_t lastKeyDownMs = 0;
// When the PTT line last came UP. The backstop below needs this as well as
// the last element: during the PTT lead-in — and through a whole RTTY over,
// or a host's manual hold — the line is legitimately up with no key-down
// behind it, and the last element can be from a transmission minutes ago.
volatile uint32_t pttUpMs = 0;
volatile bool     pttStuckCleared = false;

// Debounced paddles
uint8_t ditCnt = 0, dahCnt = 0;
volatile bool dit = false, dah = false;
bool    prevDit = false, prevDah = false;
static const uint8_t DEBOUNCE_TICKS = 3;

// ── Paddle echo decoder ───────────────────────────────────
// Accumulates the elements the OPERATOR sends and hands back finished
// characters, so a logger can capture hand-sent text (WinKeyer mode
// register bit 6). Buffered text is excluded — the host already knows
// what it asked for.
char     decPat[8];
uint8_t  decLen    = 0;
uint32_t decIdleMs = 0;
bool     decSpaceSent = true;   // suppress a leading space after silence
QueueHandle_t decodeQ = nullptr;

// Speed pot
uint32_t potAccum = 0;
uint16_t potTick  = 0;
int      potLastWpm = -1;
// The knob's own step above MINWPM, for the WinKeyer pot byte. Kept apart
// from potLastWpm, which setWpm() resets whenever a host sets a speed.
volatile int8_t potStepV = -1;
// A pot parked on a step boundary alternates between two adjacent speeds
// forever, and every flip is a speed change AND an unsolicited WinKeyer pot
// byte — at 1200 baud that stream saturates the host link.
//
// The cure is hysteresis, NOT more smoothing: a deeper filter or a
// wait-and-see settle both fix the dither by adding lag to every real
// movement too, which the operator feels immediately as a sluggish knob.
// Requiring 0.6 WPM of travel before the speed follows costs nothing on a
// deliberate turn — it acts on the very next sample — while a boundary
// flicker of ±0.5 step can never cross it.
static const int POT_HYST_CWPM = 60;   // hundredths of a WPM

void (*keyHook)(bool) = nullptr;
bool hookPaddleOnly = false;

// The hook mirrors element timing to a network backend. Buffered text keyed
// locally for sidetone must not reach it — see setHookPaddleOnly().
inline bool hookWanted() { return keyHook && !(hookPaddleOnly && curIsAuto); }

// True when this element is only a sidetone copy of text the radio is
// generating — the one case where the operator's weighting and Farnsworth
// must be ignored, so the sound matches the air. Same condition as
// hookWanted()'s exclusion, by construction.
inline bool monitorOnly() { return hookPaddleOnly && curIsAuto; }
inline uint16_t markDit()  { return monitorOnly() ? tMarkDitP : tMarkDit; }
inline uint16_t markDah()  { return monitorOnly() ? tMarkDahP : tMarkDah; }
inline uint16_t gapElem()  { return monitorOnly() ? tGapElemP : tGapElem; }
inline uint16_t gapChar()  { return monitorOnly() ? tGapCharP : tGapChar; }
inline uint16_t gapWord()  { return monitorOnly() ? tGapWordP : tGapWord; }

// ── Low-level outputs ─────────────────────────────────────
void toneOn()  { if (cfgSidetone) ledcWriteTone(PIN_SIDETONE, cfgToneHz); }
void toneOff() { ledcWriteTone(PIN_SIDETONE, 0); }
void keyDown() {
  if (cfgKeyOut) {
    if (cfgRadio & 1) digitalWrite(PIN_KEY_OUT,  HIGH);
    if (cfgRadio & 2) digitalWrite(PIN_KEY_OUT2, HIGH);
  }
  digitalWrite(PIN_STATUS_LED, HIGH);   // follows every element, any backend
  bool was = keyDownFlag;
  keyDownFlag = true;
  lastKeyDownMs = millis();
  toneOn();
  if (!was && hookWanted()) keyHook(true);
}
void keyUp() {
  digitalWrite(PIN_KEY_OUT,  LOW);   // drop both regardless of selection:
  digitalWrite(PIN_KEY_OUT2, LOW);   // a line must never be left keyed
  digitalWrite(PIN_STATUS_LED, LOW);
  bool was = keyDownFlag;
  keyDownFlag = false;
  toneOff();
  if (was && hookWanted()) keyHook(false);
}
void pttAssert() {
  // pttOn means "the LINE is up", so it must not be set when the PTT line
  // is disabled — the web page and the panel read it, and showing PTT
  // active while nothing is driven is exactly what misleads someone
  // debugging a dead PTT wire.
  if (!cfgPtt) return;
  if (cfgRadio & 1) digitalWrite(PIN_PTT_OUT,  HIGH);
  if (cfgRadio & 2) digitalWrite(PIN_PTT_OUT2, HIGH);
  // Only on the rising edge: a caller that re-asserts an already-up line
  // (the Flex backend polls, a host can repeat 0x18) must not be able to
  // push the backstop's deadline forward for ever.
  if (!pttOn) pttUpMs = millis();
  pttOn = true;
}
void pttRelease() {
  if (flagPttHold) return;          // host is holding PTT down explicitly
  digitalWrite(PIN_PTT_OUT,  LOW);
  digitalWrite(PIN_PTT_OUT2, LOW);
  pttOn = false;
}

// ── State machine helpers ─────────────────────────────────
void startElement(bool isDah, bool isAuto) {
  if (!isAuto) {                       // paddle-sent: remember the shape
    if (decLen < sizeof(decPat) - 1) decPat[decLen++] = isDah ? '-' : '.';
    decIdleMs = 0;
  }
  curIsDah   = isDah;
  curIsAuto  = isAuto;
  lastWasDah = isDah;
  if (isDah) memDah = false; else memDit = false;
  keyDown();
  state   = ST_KEYDOWN;
  timerMs = isDah ? markDah() : markDit();
}

void goIdle() {
  pattern = nullptr;
  memDit = memDah = false;
  mergeNext = false;
  state = ST_IDLE;
  tailTimer = cfgTailMs;
}

// Decide what happens after a gap expires (also entered from IDLE/LEAD
// when work appears).
void decideNext() {
  // Paddles first. Mode B considers latched memory; mode A only live paddles.
  bool wantDit = dit || (cfgMode == KEYER_IAMBIC_B && memDit);
  bool wantDah = dah || (cfgMode == KEYER_IAMBIC_B && memDah);
  if (wantDit && wantDah) { startElement(!lastWasDah, false); return; }  // squeeze alternates
  if (wantDit)            { startElement(false, false);       return; }
  if (wantDah)            { startElement(true,  false);       return; }

  // Continue the character in progress.
  if (pattern && *pattern) { startElement(*pattern++ == '-', true); return; }
  if (pattern) {
    // Character finished. One element gap has already elapsed; add the rest
    // of the inter-character space unless a merge (prosign) suppressed it.
    pattern = nullptr;
    if (mergeNext) { mergeNext = false; decideNext(); return; }
    state = ST_GAP;
    timerMs = gapChar();
    return;
  }

  // Pop the next buffered item.
  char c;
  while (xQueueReceive(charQ, &c, 0) == pdTRUE) {
    if (c == KEYER_MERGE_MARK) { mergeNext = true; continue; }
    if (c == ' ') {                    // word gap, on top of the character gap
      state = ST_GAP;
      timerMs = gapWord();
      return;
    }
    pattern = morseFor(c);
    if (pattern && *pattern) { startElement(*pattern++ == '-', true); return; }
    pattern = nullptr;                 // unknown char — skip it
  }

  goIdle();
}

// Begin activity out of idle: honour PTT lead-in before the first element.
void startActivity() {
  if (cfgPtt && !pttOn && cfgLeadMs) {
    if (cfgPttAuto) pttAssert();
    state = ST_LEAD;
    timerMs = cfgLeadMs;
  } else {
    if (cfgPttAuto) pttAssert();
    decideNext();
  }
}

// ── Paddle sampling ───────────────────────────────────────
void samplePaddles() {
  bool rawDit = !digitalRead(cfgSwap ? PIN_PADDLE_DAH : PIN_PADDLE_DIT);
  bool rawDah = !digitalRead(cfgSwap ? PIN_PADDLE_DIT : PIN_PADDLE_DAH);
  ditCnt = rawDit ? min<uint8_t>(ditCnt + 1, DEBOUNCE_TICKS) : 0;
  dahCnt = rawDah ? min<uint8_t>(dahCnt + 1, DEBOUNCE_TICKS) : 0;
  prevDit = dit; prevDah = dah;
  dit = ditCnt >= DEBOUNCE_TICKS;
  dah = dahCnt >= DEBOUNCE_TICKS;
}

// ── Speed pot ─────────────────────────────────────────────
// Absolute backstop on the PTT line. Everything that sequences it —
// the keyer's own tail, a host's manual hold, the Flex backend driving it
// from the radio's progress — can be defeated by one lost transition, and
// the cost is a transmitter left keyed. Nothing legitimate holds PTT with
// no keying for this long except tune, which is excluded.
static const uint32_t PTT_MAX_IDLE_MS = 10000;

// The deadline runs from the last sign of life on the line, which is the
// LATER of "PTT came up" and "an element was keyed" — not the element alone.
// Timing it from the element alone made the backstop fire one millisecond
// into the PTT lead-in of any transmission that started more than 10 s after
// the previous one: PTT flicked on and straight back off, the whole over
// went out with no PTT, and the next over (keyed while the stamp was still
// fresh) was fine. Nothing was stuck; the reference was simply stale.
void pttSafety() {
  if (!pttOn || flagTune) return;
  if (keyDownFlag) { return; }
  uint32_t ref = pttUpMs;
  if (lastKeyDownMs && (int32_t)(lastKeyDownMs - ref) > 0) ref = lastKeyDownMs;
  if (ref && (millis() - ref) > PTT_MAX_IDLE_MS) {
    digitalWrite(PIN_PTT_OUT, LOW);
    digitalWrite(PIN_PTT_OUT2, LOW);
    pttOn = false;
    pttStuckCleared = true;      // reported once from loop context
  }
}

void samplePot() {
  if (!cfgPotEn) return;
  if (++potTick < 50) return;          // one reading per 50 ms
  potTick = 0;
  potAccum = (potAccum * 3 + (uint32_t)analogRead(PIN_SPEED_POT)) / 4;  // IIR smooth
  // Work in hundredths so the deadband can sit between two whole WPM steps.
  int cwpm = (int)cfgPotMin * 100 + (int)((potAccum * cfgPotRange * 100) / 4095);
  if (potLastWpm < 0) {                   // don't stomp boot speed
    potLastWpm = (cwpm + 50) / 100;
    potStepV = (int8_t)constrain(potLastWpm - (int)cfgPotMin, 0, (int)cfgPotRange);
    return;
  }
  int cur = potLastWpm * 100;
  if (cwpm < cur + POT_HYST_CWPM && cwpm > cur - POT_HYST_CWPM) return;
  potLastWpm = (cwpm + 50) / 100;
  potStepV = (int8_t)constrain(potLastWpm - (int)cfgPotMin, 0, (int)cfgPotRange);
  cfgWpm     = constrain(potLastWpm, 5, 60);
  recalc();
}

// Called once per millisecond. A character ends after 2 dit-times of
// silence (the element gap is 1, the inter-character gap 3), and a word
// after 5 — comfortably inside the standard gaps at any speed, because the
// gaps scale with WPM and so does tGapElem.
void tickDecoder() {
  if (decLen == 0 && decSpaceSent) return;
  if (state == ST_KEYDOWN || state == ST_TUNE) { decIdleMs = 0; return; }
  decIdleMs++;

  if (decLen > 0 && decIdleMs >= (uint32_t)tGapElem * 2) {
    decPat[decLen] = '\0';
    char c = charFor(decPat);
    decLen = 0;
    if (c && decodeQ) xQueueSend(decodeQ, &c, 0);
    decSpaceSent = false;
  } else if (!decSpaceSent && decIdleMs >= (uint32_t)tGapElem * 5) {
    char sp = ' ';
    if (decodeQ) xQueueSend(decodeQ, &sp, 0);
    decSpaceSent = true;
  }
}

// ── The 1 kHz keyer task ──────────────────────────────────
void keyerTask(void*) {
  TickType_t wake = xTaskGetTickCount();
  for (;;) {
    vTaskDelayUntil(&wake, pdMS_TO_TICKS(1));
    samplePaddles();
    samplePot();
    pttSafety();
    tickDecoder();

    // Paddle session for WinKeyer BREAKIN. A paddle element in progress or
    // in its gap counts as activity; tune and buffered text do not.
    if (dit || dah || (!curIsAuto && (state == ST_KEYDOWN || state == ST_GAP))) {
      paddleSess = true;
      paddleIdleMs = 0;
    } else if (paddleSess && ++paddleIdleMs >= (uint32_t)tGapElemP * 8) {
      paddleSess = false;
    }

    // Host abort (WK "clear buffer"): stop buffered sending at once.
    if (flagClear) {
      flagClear = false;
      xQueueReset(charQ);
      pattern = nullptr;
      mergeNext = false;
      if (curIsAuto && state == ST_KEYDOWN) { keyUp(); goIdle(); }
      else if (state == ST_GAP)             { goIdle(); }
    }

    // Paddle break-in: a fresh paddle press aborts buffered sending.
    bool paddleEdge = (dit && !prevDit) || (dah && !prevDah);
    if (paddleEdge && (pattern || uxQueueMessagesWaiting(charQ) > 0)) {
      xQueueReset(charQ);
      pattern = nullptr;
      mergeNext = false;
      if (curIsAuto && state == ST_KEYDOWN) { keyUp(); state = ST_GAP; timerMs = gapElem(); }
    }

    // Tune mode overrides everything.
    if (flagTune && state != ST_TUNE) {
      keyUp();
      pattern = nullptr;
      // Tune is an operator action, not buffered text: it must reach the
      // key hook (and so the radio) even when buffered elements are being
      // keyed locally for sidetone only. curIsAuto is otherwise stale from
      // whatever element ran last.
      curIsAuto = false;
      if (cfgPttAuto) pttAssert();
      keyDown();
      state = ST_TUNE;
    }

    switch (state) {
      case ST_TUNE:
        if (!flagTune) { keyUp(); goIdle(); }
        break;

      case ST_IDLE:
        if (dit || dah || uxQueueMessagesWaiting(charQ) > 0) {
          // Latch the triggering paddle so a quick tap survives the PTT lead.
          if (dit) memDit = true;
          if (dah) memDah = true;
          startActivity();
        } else if (pttOn) {
          if (tailTimer > 0) tailTimer--;
          if (tailTimer == 0 && cfgPttAuto) pttRelease();
        }
        break;

      case ST_LEAD:
        if (dit) memDit = true;        // keep latching through the lead-in
        if (dah) memDah = true;
        if (timerMs > 0) timerMs--;
        if (timerMs == 0) decideNext();
        break;

      case ST_KEYDOWN:
        // Both iambic modes latch the opposite paddle during an element.
        if (curIsDah && dit) memDit = true;
        if (!curIsDah && dah) memDah = true;
        if (timerMs > 0) timerMs--;
        if (timerMs == 0) {
          keyUp();
          state = ST_GAP;
          timerMs = gapElem();         // inter-element space
        }
        break;

      case ST_GAP:
        // Mode B also latches during the space; mode A decides live.
        if (cfgMode == KEYER_IAMBIC_B) {
          if (dit) memDit = true;
          if (dah) memDah = true;
        }
        if (timerMs > 0) timerMs--;
        if (timerMs == 0) decideNext();
        break;
    }
  }
}

}  // namespace

// ── Public API ────────────────────────────────────────────
namespace Keyer {

void begin() {
  pinMode(PIN_PADDLE_DIT, INPUT_PULLUP);
  pinMode(PIN_PADDLE_DAH, INPUT_PULLUP);
  // Radio 2's pair was written without ever being declared — silently
  // accepted by core 2.0.17, refused by 3.x ("IO 18 is not set as GPIO"),
  // which means those lines were never actually driven low at boot.
  pinMode(PIN_KEY_OUT,  OUTPUT);  digitalWrite(PIN_KEY_OUT,  LOW);
  pinMode(PIN_KEY_OUT2, OUTPUT);  digitalWrite(PIN_KEY_OUT2, LOW);
  pinMode(PIN_PTT_OUT,  OUTPUT);  digitalWrite(PIN_PTT_OUT,  LOW);
  pinMode(PIN_PTT_OUT2, OUTPUT);  digitalWrite(PIN_PTT_OUT2, LOW);

  // Arduino core 3.x addresses LEDC by PIN, not by channel — ledcSetup()
  // and ledcAttachPin() are gone; ledcAttach() does both.
  ledcAttach(PIN_SIDETONE, cfgToneHz, 10);
  ledcWriteTone(PIN_SIDETONE, 0);

  // The ADC channel has to exist before its attenuation can be set, and
  // what creates it is a first read — pinMode alone is not enough on
  // core 3.x ("Pin is not configured as analog channel").
  pinMode(PIN_SPEED_POT, INPUT);
  (void)analogRead(PIN_SPEED_POT);
  analogSetPinAttenuation(PIN_SPEED_POT, ADC_11db);   // full 0–3.3 V range

  recalc();
  charQ   = xQueueCreate(256, sizeof(char));
  decodeQ = xQueueCreate(64, sizeof(char));

  // Priority well above loopTask (1); pinned to core 1 alongside it —
  // WiFi/BT stacks live on core 0 and never preempt element timing.
  xTaskCreatePinnedToCore(keyerTask, "keyer", 4096, nullptr, 10, nullptr, 1);
}

void setWpm(uint8_t wpm) {
  cfgWpm = constrain(wpm, (uint8_t)5, (uint8_t)60);
  recalc();
  potLastWpm = -1;   // host speed rules until the pot moves again
}
uint8_t   getWpm()  { return cfgWpm; }
void      setMode(KeyerMode m) { cfgMode = m; }
KeyerMode getMode() { return cfgMode; }
void      setPaddleSwap(bool s) { cfgSwap = s; }
bool      getPaddleSwap() { return cfgSwap; }
void      setSidetone(bool en) { cfgSidetone = en; if (!en) toneOff(); }
bool      getSidetone() { return cfgSidetone; }
// 300-1000 Hz. The upper bound used to be 2000 because that is what the
// host command can ask for (it sends 4000/N, so N=2 means 2000), but a
// tone nobody wants to listen to is not worth a range that squeezes the
// 500-800 anyone actually uses into a quarter of the slider. A host
// asking for more is clamped, and that setting dies with its session.
void      setSidetoneHz(uint16_t hz) { cfgToneHz = constrain(hz, (uint16_t)300, (uint16_t)1000); }
uint16_t  getSidetoneHz() { return cfgToneHz; }
void      setPttEnabled(bool en) {
  cfgPtt = en;
  if (!en) { digitalWrite(PIN_PTT_OUT, LOW); digitalWrite(PIN_PTT_OUT2, LOW); }
}
bool      getPttEnabled() { return cfgPtt; }
void      setPttLeadMs(uint16_t ms) { cfgLeadMs = ms; }
uint16_t  getPttLeadMs() { return cfgLeadMs; }
void      setPttTailMs(uint16_t ms) { cfgTailMs = ms; }
uint16_t  getPttTailMs() { return cfgTailMs; }
void      setPotEnabled(bool en) { cfgPotEn = en; potLastWpm = -1; }
bool      getPotEnabled() { return cfgPotEn; }
void      setPotRange(uint8_t minWpm, uint8_t range) { cfgPotMin = minWpm; cfgPotRange = range; potLastWpm = -1; }
uint8_t   getPotMin()   { return cfgPotMin; }
uint8_t   getPotRange() { return cfgPotRange; }
void      setKeyOutEnabled(bool en) {
  cfgKeyOut = en;
  if (!en) { digitalWrite(PIN_KEY_OUT, LOW); digitalWrite(PIN_KEY_OUT2, LOW); }
}

// Switching radios mid-transmission would strand the outgoing one keyed,
// so everything drops first and the new selection picks up on the next
// element.
void setPttAuto(bool on) { cfgPttAuto = on; }

void setRadio(uint8_t sel) {
  if (!(sel & 3)) return;
  digitalWrite(PIN_KEY_OUT,  LOW); digitalWrite(PIN_KEY_OUT2, LOW);
  digitalWrite(PIN_PTT_OUT,  LOW); digitalWrite(PIN_PTT_OUT2, LOW);
  pttOn = false;
  cfgRadio = sel & 3;
}
uint8_t getRadio() { return cfgRadio; }
void      setWeighting(uint8_t w) { cfgWeight = constrain(w, (uint8_t)10, (uint8_t)90); recalc(); }
uint8_t   getWeighting()  { return cfgWeight; }
void      setRatio(uint8_t r)     { cfgRatio  = constrain(r, (uint8_t)33, (uint8_t)66); recalc(); }
uint8_t   getRatio()      { return cfgRatio; }
void      setFarnsworth(uint8_t w){ cfgFarns  = w; recalc(); }
uint8_t   getFarnsworth() { return cfgFarns; }

bool sendChar(char c) {
  if (c != KEYER_MERGE_MARK) {
    c = toupper((unsigned char)c);
    if (c != ' ' && !morseFor(c)) return true;   // silently skip unknown chars
  }
  return xQueueSend(charQ, &c, 0) == pdTRUE;
}

size_t queueDepth() { return charQ ? uxQueueMessagesWaiting(charQ) : 0; }

void clearBuffer() { flagClear = true; }
void tune(bool on) { flagTune = on; }
bool tuning()      { return flagTune; }

void pttManual(bool on) {
  flagPttHold = on;
  if (on) { if (cfgPtt) pttAssert(); return; }

  // Releasing was gated on the keyer being idle, which is right only while
  // the keyer owns the line: it stops a host's PTT-off from cutting a
  // transmission short. When something else owns it (cfgPttAuto false, as
  // on the Flex backend) that gate is fatal — the keyer is still playing
  // the monitor copy when the radio finishes, so the release was skipped
  // and, with the keyer's own tail disabled, NOTHING else could drop it.
  // The transmitter stayed keyed.
  if (!cfgPttAuto || state == ST_IDLE) {
    digitalWrite(PIN_PTT_OUT, LOW); digitalWrite(PIN_PTT_OUT2, LOW);
    pttOn = false;
  }
}

bool busy()         { return state != ST_IDLE || queueDepth() > 0; }
bool keyIsDown()    { return keyDownFlag; }
bool pttIsOn() { return pttOn; }

void pttKeepAlive() { if (pttOn) pttUpMs = millis(); }

bool pttStuckWasCleared() {
  bool b = pttStuckCleared;
  pttStuckCleared = false;
  return b;
}

void chirp(char c) {
  const char* pat = morseFor(toupper((unsigned char)c));
  if (!pat) return;
  uint16_t dit = 1200 / (cfgWpm ? cfgWpm : 20);
  for (const char* p = pat; *p; p++) {
    ledcWriteTone(PIN_SIDETONE, cfgToneHz);
    delay(*p == '-' ? dit * 3 : dit);
    ledcWriteTone(PIN_SIDETONE, 0);
    delay(dit);
  }
}

uint32_t msSinceKey() {
  return lastKeyDownMs ? (millis() - lastKeyDownMs) : 0xFFFFFFFF;
}
bool paddleActive() { return dit || dah; }
bool paddleDit()    { return dit; }
bool paddleDah()    { return dah; }

void setKeyEventHook(void (*fn)(bool)) { keyHook = fn; }
void setHookPaddleOnly(bool on) { hookPaddleOnly = on; }

bool decodedRead(char& c) {
  return decodeQ && xQueueReceive(decodeQ, &c, 0) == pdTRUE;
}

bool   paddleSession() { return paddleSess; }
int8_t potStep()       { return cfgPotEn ? potStepV : -1; }

}  // namespace Keyer
